Pull additional tags in docker-pull
FairwindsOps/rok8s-scripts pull request #364
Opened 2020-09-08 21:47 UTC by rbren

We could use this as part of the insights-plugins pipeline.  I think it's generally useful as well.

2020-09-08 21:51 UTC, sudermanjr requested changes
Can you please document this somewhere in docs?

2020-09-09 11:53 UTC, rbren commented
Couldn't find any existing docs for this var, so I started creating a list of vars in docker.md. LMK if I missed any.

2020-09-09 20:23 UTC, lucasreed approved these changes

2020-09-09 23:04 UTC, sudermanjr approved these changes

2020-09-09 23:04 UTC, merged